/**
 * Iraqi governorates for the "المحافظة" picker. Value === Arabic label.
 * Shared across every farm-type feature (poultry/sheep/cattle), the
 * poultry-market feature and registration — genuinely generic geography data.
 * Mirrors the server list (`server/src/shared/validation/geography.ts`).
 */
export const IRAQ_GOVERNORATES: readonly string[] = [
  'بغداد',
  'البصرة',
  'نينوى',
  'أربيل',
  'النجف',
  'كربلاء',
  'بابل',
  'ذي قار',
  'الأنبار',
  'ديالى',
  'كركوك',
  'صلاح الدين',
  'واسط',
  'ميسان',
  'المثنى',
  'القادسية',
  'دهوك',
  'السليمانية',
  'حلبجة',
];

/**
 * First-level administrative regions (governorates / provinces / states /
 * emirates) per ISO-3166 alpha-2 country — one list for every country the
 * registration `CountrySelect` offers, so picking e.g. Egypt shows Egyptian
 * governorates, never Iraqi ones. A country without an entry falls back to a
 * free-text field (`governoratesFor` → `null`). Mirrors the server
 * (`server/src/shared/validation/geography.ts`) — add a country in BOTH.
 */
export const GOVERNORATES_BY_COUNTRY: Readonly<Record<string, readonly string[]>> = {
  IQ: IRAQ_GOVERNORATES,
  SA: [
    'الرياض',
    'مكة المكرمة',
    'المدينة المنورة',
    'القصيم',
    'المنطقة الشرقية',
    'عسير',
    'تبوك',
    'حائل',
    'الحدود الشمالية',
    'جازان',
    'نجران',
    'الباحة',
    'الجوف',
  ],
  AE: ['أبوظبي', 'دبي', 'الشارقة', 'عجمان', 'أم القيوين', 'رأس الخيمة', 'الفجيرة'],
  KW: ['العاصمة', 'حولي', 'الفروانية', 'الأحمدي', 'الجهراء', 'مبارك الكبير'],
  QA: ['الدوحة', 'الريان', 'الوكرة', 'الخور', 'الشمال', 'أم صلال', 'الظعاين', 'الشحانية'],
  BH: ['العاصمة', 'المحرق', 'الشمالية', 'الجنوبية'],
  OM: [
    'مسقط',
    'ظفار',
    'مسندم',
    'البريمي',
    'الداخلية',
    'شمال الباطنة',
    'جنوب الباطنة',
    'شمال الشرقية',
    'جنوب الشرقية',
    'الظاهرة',
    'الوسطى',
  ],
  EG: [
    'القاهرة',
    'الجيزة',
    'الإسكندرية',
    'القليوبية',
    'الشرقية',
    'الدقهلية',
    'الغربية',
    'المنوفية',
    'البحيرة',
    'كفر الشيخ',
    'دمياط',
    'بورسعيد',
    'الإسماعيلية',
    'السويس',
    'شمال سيناء',
    'جنوب سيناء',
    'الفيوم',
    'بني سويف',
    'المنيا',
    'أسيوط',
    'سوهاج',
    'قنا',
    'الأقصر',
    'أسوان',
    'البحر الأحمر',
    'الوادي الجديد',
    'مطروح',
  ],
  JO: [
    'عمان',
    'إربد',
    'الزرقاء',
    'البلقاء',
    'المفرق',
    'جرش',
    'عجلون',
    'مأدبا',
    'الكرك',
    'الطفيلة',
    'معان',
    'العقبة',
  ],
  LB: [
    'بيروت',
    'جبل لبنان',
    'كسروان جبيل',
    'الشمال',
    'عكار',
    'البقاع',
    'بعلبك الهرمل',
    'الجنوب',
    'النبطية',
  ],
  SY: [
    'دمشق',
    'ريف دمشق',
    'حلب',
    'حمص',
    'حماة',
    'اللاذقية',
    'طرطوس',
    'إدلب',
    'الحسكة',
    'دير الزور',
    'الرقة',
    'درعا',
    'السويداء',
    'القنيطرة',
  ],
  YE: [
    'أمانة العاصمة',
    'صنعاء',
    'عدن',
    'تعز',
    'الحديدة',
    'إب',
    'ذمار',
    'حضرموت',
    'المهرة',
    'شبوة',
    'أبين',
    'لحج',
    'الضالع',
    'البيضاء',
    'مأرب',
    'الجوف',
    'صعدة',
    'عمران',
    'حجة',
    'المحويت',
    'ريمة',
    'سقطرى',
  ],
  PS: [
    'القدس',
    'رام الله والبيرة',
    'بيت لحم',
    'الخليل',
    'نابلس',
    'جنين',
    'طولكرم',
    'قلقيلية',
    'سلفيت',
    'طوباس',
    'أريحا والأغوار',
    'شمال غزة',
    'غزة',
    'دير البلح',
    'خان يونس',
    'رفح',
  ],
  LY: [
    'طرابلس',
    'بنغازي',
    'مصراتة',
    'الزاوية',
    'الجفارة',
    'الجبل الغربي',
    'نالوت',
    'النقاط الخمس',
    'المرقب',
    'سرت',
    'الجفرة',
    'الواحات',
    'الكفرة',
    'المرج',
    'الجبل الأخضر',
    'درنة',
    'البطنان',
    'سبها',
    'وادي الشاطئ',
    'وادي الحياة',
    'مرزق',
    'غات',
  ],
  TN: [
    'تونس',
    'أريانة',
    'بن عروس',
    'منوبة',
    'نابل',
    'زغوان',
    'بنزرت',
    'باجة',
    'جندوبة',
    'الكاف',
    'سليانة',
    'سوسة',
    'المنستير',
    'المهدية',
    'صفاقس',
    'القيروان',
    'القصرين',
    'سيدي بوزيد',
    'قابس',
    'مدنين',
    'تطاوين',
    'قفصة',
    'توزر',
    'قبلي',
  ],
  DZ: [
    'أدرار',
    'الشلف',
    'الأغواط',
    'أم البواقي',
    'باتنة',
    'بجاية',
    'بسكرة',
    'بشار',
    'البليدة',
    'البويرة',
    'تمنراست',
    'تبسة',
    'تلمسان',
    'تيارت',
    'تيزي وزو',
    'الجزائر',
    'الجلفة',
    'جيجل',
    'سطيف',
    'سعيدة',
    'سكيكدة',
    'سيدي بلعباس',
    'عنابة',
    'قالمة',
    'قسنطينة',
    'المدية',
    'مستغانم',
    'المسيلة',
    'معسكر',
    'ورقلة',
    'وهران',
    'البيض',
    'إليزي',
    'برج بوعريريج',
    'بومرداس',
    'الطارف',
    'تندوف',
    'تيسمسيلت',
    'الوادي',
    'خنشلة',
    'سوق أهراس',
    'تيبازة',
    'ميلة',
    'عين الدفلى',
    'النعامة',
    'عين تموشنت',
    'غرداية',
    'غليزان',
    'تيميمون',
    'برج باجي مختار',
    'أولاد جلال',
    'بني عباس',
    'عين صالح',
    'عين قزام',
    'تقرت',
    'جانت',
    'المغير',
    'المنيعة',
  ],
  MA: [
    'طنجة تطوان الحسيمة',
    'الشرق',
    'فاس مكناس',
    'الرباط سلا القنيطرة',
    'بني ملال خنيفرة',
    'الدار البيضاء سطات',
    'مراكش آسفي',
    'درعة تافيلالت',
    'سوس ماسة',
    'كلميم واد نون',
    'العيون الساقية الحمراء',
    'الداخلة وادي الذهب',
  ],
  SD: [
    'الخرطوم',
    'الجزيرة',
    'النيل الأبيض',
    'النيل الأزرق',
    'سنار',
    'القضارف',
    'كسلا',
    'البحر الأحمر',
    'نهر النيل',
    'الشمالية',
    'شمال كردفان',
    'جنوب كردفان',
    'غرب كردفان',
    'شمال دارفور',
    'جنوب دارفور',
    'شرق دارفور',
    'غرب دارفور',
    'وسط دارفور',
  ],
  MR: [
    'الحوض الشرقي',
    'الحوض الغربي',
    'لعصابة',
    'كوركول',
    'البراكنة',
    'الترارزة',
    'آدرار',
    'داخلت نواذيبو',
    'تكانت',
    'كيدي ماغا',
    'تيرس زمور',
    'إينشيري',
    'نواكشوط الشمالية',
    'نواكشوط الغربية',
    'نواكشوط الجنوبية',
  ],
  SO: [
    'أودل',
    'أوال',
    'صناج',
    'سول',
    'بري',
    'نوغال',
    'مدق',
    'جلجدود',
    'هيران',
    'شبيلي الوسطى',
    'بنادر',
    'شبيلي السفلى',
    'باي',
    'بكول',
    'جدو',
    'جوبا الوسطى',
    'جوبا السفلى',
    'توغدير',
  ],
  DJ: ['جيبوتي', 'علي صبيح', 'دخيل', 'تاجورة', 'أوبوك', 'عرتا'],
  KM: ['القمر الكبرى', 'أنجوان', 'موهيلي'],
};

export function governoratesFor(country: string | null | undefined): readonly string[] | null {
  if (!country) return null;
  return GOVERNORATES_BY_COUNTRY[country.toUpperCase()] ?? null;
}

/**
 * The four governorates of the Kurdistan Region. On the poultry / egg
 * exchange (bourse) they are NOT priced separately: one "إقليم كوردستان"
 * entry with ONE price covers all four (final corrections §8). The server
 * validates the same market list (`poultryMarket/domain/market-governorates.ts`).
 */
export const KURDISTAN_REGION_GOVERNORATES: readonly string[] = [
  'أربيل',
  'دهوك',
  'السليمانية',
  'حلبجة',
];

/** The single exchange entry (and stored rate key) for the Kurdistan Region. */
export const KURDISTAN_REGION_MARKET_KEY = 'إقليم كوردستان';

export type GovernorateMarketRow = { kind: 'governorate'; governorate: string };

/**
 * The exchange boards' rows: every Iraqi governorate in canonical order, with
 * the Kurdistan Region's four replaced by ONE "إقليم كوردستان" row at the
 * position of the first of them.
 */
export function governoratesForMarket(): GovernorateMarketRow[] {
  const rows: GovernorateMarketRow[] = [];
  let regionAdded = false;
  for (const governorate of IRAQ_GOVERNORATES) {
    if (KURDISTAN_REGION_GOVERNORATES.includes(governorate)) {
      if (!regionAdded) {
        rows.push({ kind: 'governorate', governorate: KURDISTAN_REGION_MARKET_KEY });
        regionAdded = true;
      }
      continue;
    }
    rows.push({ kind: 'governorate', governorate });
  }
  return rows;
}
