export {
  useSyndicateMediaProvider,
  useMainSyndicates,
  useSyndicate,
  useMySyndicateAccess,
  useSyndicateBranches,
  useUpdateSyndicateProfile,
  useFollowSyndicate,
  useUnfollowSyndicate,
  useSyndicateAnnouncements,
  useSyndicateAnnouncement,
  useCreateSyndicateAnnouncement,
  useUpdateSyndicateAnnouncement,
  useDeleteSyndicateAnnouncement,
  useCreateSyndicateSubmission,
  useSyndicateSubmissions,
  useSyndicateSubmission,
  useRespondToSyndicateSubmission,
  useCloseSyndicateSubmission,
  useMySyndicateSubmissions,
  useMySyndicateSubmission,
} from './useSyndicates';
export { useCreateSyndicateAdmin } from './useAdminSyndicates';
